### ISSUE TITLE
A zero-length extent is returned if the file has no extents

### ISSUE THREAD

**Issue by tarka** [lilydjwg/fiemap-rs#1]
To reproduce:
* `truncate -s 1M /tmp/sparse.bin`
* `cargo run --example show_extents /tmp/sparse.bin`

Expected:
* No extents shown.

Actual:
* `FiemapExtent { fe_logical: 0, fe_physical: 0, fe_length: 0, fe_flags: (empty) }`

The issue appears to be in the iterator, where it is not checking the number of extents return by `get_extents()` before returning `Some(Ok(self.fiemap.fm_extents[idx]))`.

**Comment by lilydjwg** [comment]
Thanks! This has been fixed.
